name: No Free usage issue checker

# æœ‰è¶£çš„action

on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Check issue actor
      uses: fluttercandies/no-free-usage-action@v1.0.1
        with:
          # ç”±GitHubæä¾›çš„ä¸´æ—¶Tokenï¼Œå¿…é¡»åœ¨æ­¤å¤„è¿›è¡Œä¼ é€’ï¼Œä¸”å¿…é¡»ä¸ºè¿™ä¸ªå€¼ã€‚
          forked: '--no-forked'
          token: ${{ secrets.GITHUB_TOKEN }}  
          words:  ä¸ºäº†æ”¯æŒæˆ‘ä»¬çš„é¡¹ç›®ï¼Œè¯·æ‚¨åœ¨ç‚¹èµè¯¥ä»“åº“åæäº¤é—®é¢˜ã€‚è°¢è°¢ï¼To support our project, please file the issue after you starred the repo. Thanks! ğŸ™‚ ä½œè€…ï¼šbiewang